const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{agua: 0},
	{Texto: 0},
	{Texto2: 0},
	{JOGARNOVA: 0},
	{VOLTARAOINICIO: 0},
	{Texto3: 0},
	{Texto4: 0},
	{irAFase1: 0},
	{Botão: 0},
	{Texto5: 0},
	{voltarAoInico: 0},
	{c483ff16585f1014ce8bff226bc: 0},
	{Sólido: 0},
	{chão: 0},
	{pixelartplatformssetgame260nw2513324719removebgpreview: 0},
	{Texto6: 0},
	{proximos: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{boneca: 0},
	{WhatsApp_Image_20250404_at_081604removebgpreview: 0},
	{Teclado: 0},
	{Senóide: 0},
	{inimigo: 0},
	{pc: 0},
	{AlbedoBase_XL_create_a_scene_in_a_dense_and_closed_jungle_: 0},
	{AlbedoBase_XL_create_a_scene_in_a_dense_and_night_jungle_: 0},
	{AlbedoBase_XL_create_a_scene_in_a_dense_and_jungle_: 0},
	{AlbedoBase_XL_create_a_scene_in_a_dense_and_dawn_jungle_: 0},
	{ChatGPT_Image_28_04_2025__15_30_43removebgpreview: 0},
	{cu: 0},
	{w058n003284Bp: 0},
	{macaco: 0}
];

self.InstanceType = {
	agua: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Texto2: class extends self.ITextInstance {},
	JOGARNOVA: class extends self.IButtonInstance {},
	VOLTARAOINICIO: class extends self.IButtonInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto4: class extends self.ITextInstance {},
	irAFase1: class extends self.IButtonInstance {},
	Botão: class extends self.IButtonInstance {},
	Texto5: class extends self.ITextInstance {},
	voltarAoInico: class extends self.IButtonInstance {},
	c483ff16585f1014ce8bff226bc: class extends self.ISpriteInstance {},
	chão: class extends self.ISpriteInstance {},
	pixelartplatformssetgame260nw2513324719removebgpreview: class extends self.ISpriteInstance {},
	Texto6: class extends self.ITextInstance {},
	proximos: class extends self.IButtonInstance {},
	boneca: class extends self.ISpriteInstance {},
	WhatsApp_Image_20250404_at_081604removebgpreview: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	inimigo: class extends self.ISpriteInstance {},
	pc: class extends self.ISpriteInstance {},
	AlbedoBase_XL_create_a_scene_in_a_dense_and_closed_jungle_: class extends self.ISpriteInstance {},
	AlbedoBase_XL_create_a_scene_in_a_dense_and_night_jungle_: class extends self.ISpriteInstance {},
	AlbedoBase_XL_create_a_scene_in_a_dense_and_jungle_: class extends self.ISpriteInstance {},
	AlbedoBase_XL_create_a_scene_in_a_dense_and_dawn_jungle_: class extends self.ISpriteInstance {},
	ChatGPT_Image_28_04_2025__15_30_43removebgpreview: class extends self.ISpriteInstance {},
	cu: class extends self.ISpriteInstance {},
	w058n003284Bp: class extends self.ISpriteInstance {},
	macaco: class extends self.ISpriteInstance {}
}